### ISSUE TITLE
Not working in latest version of Chrome

### ISSUE THREAD

**Issue by agami** [andygott/Really-Simple-Slideshow#6]
12.0.742.91 on Mac.

**Comment by andygott** [comment]
Can you provide more information about the problem you're having? I don't seem to have any issues, using the same version of Chrome.

Andy

**Comment by agami** [comment]
On Mac 10.6.7 - none of the demos on the site work (i.e. they dont scroll - you just see the first slide and that's it). Couldn't get it to work on our site either.

Anything I can provide that might be helpful to figure it out?

**Comment by ghost** [comment]
Same here: I see the first, static image of each slideshow in Chrome, but the slideshows are not initialized (at least that´s what it looks like).  

I´m using Chrome 13.0.782.32 beta on Windows Vista. My version of Chrome is still in beta, but since agami saw the same error in Chrome 10 I doubt that that´s the problem. Strangely I didn´t see any errors in Chrome´s JS console. 

In IE 8, there are no transition effects between the images. They simple jump from one to another, without fading or sliding.  

Is there anything I can do to help troubleshoot? The lazy loading feature and file size make it a unique plugin, I´d love to use it in my projects!

**Comment by andygott** [comment]
I can't replicate this issue at all. Are you experiencing this when running the demos locally, and with no alterations to the markup/ bootstrap files?

**Comment by agami** [comment]
That and on the website demo as well.

OS X 10.6.8, Chrome 13.0.782.41 beta

I can't replicate this issue at all. Are you experiencing this when running

**Comment by ghost** [comment]
I´m only referring to the website demos on this page: http://reallysimpleworks.com/slideshow/

Today I´m using a different PC and I´m experiencing the same issues (in Chrome and IE). My set up is Chrome 12.0.742.112 + Windows XP. Also using IE8.

**Comment by andygott** [comment]
I'll keep looking into this today. 

I've also created a separate issue for the broken fade effect in IE8, which we're working on today: https://github.com/reallysimple/Really-Simple-Slideshow/issues/7

**Comment by andygott** [comment]
I still haven't managed to replicate this issue, but I've just deployed an updated version to the page at:

http://reallysimpleworks.com/slideshow/

As I haven't been able to replicate this, I'm working in the dark, so if you could you let me know if you're still having the same issue, that'd be great. Thanks.

**Comment by ghost** [comment]
Mmm strange things are hapenning: 

I opened http://reallysimpleworks.com/slideshow/ in Chrome Incognito mode, and it works! I see the images fading. 

That made me think it might be a conflict with a Chrome Extension. When I tried to verify that (in standard mode) by disabling all extensions and browsing to http://reallysimpleworks.com/slideshow/ , the server sent me the plain, non-interpreted  PHP file starting with ```<?php $page = array( 'title' => 'Really Simple™ Slideshow´´´´ etc. - Chrome doesn´t know how to open this, so it started downloading the file.

**Comment by agami** [comment]
Not getting that, but the slideshow still isn't progressing past slide one.
I do see this in the console though:

"Viewport argument value "device-width;" for key "width" not recognized.
Content ignored."

**Comment by agami** [comment]
Also:

"Viewport argument value "1.0;" for key "initial-scale" was truncated to its
numeric prefix."

**Comment by andygott** [comment]
The viewport-argument errors are normal: they're there for mobile Safari – Chrome will ignore them.

@agami If the slideshow was working for Mattvic (however briefly), you may be getting a cached version of the page. Have you refreshed the browser?

@Mattvic We had some server trouble yesterday, which meant PHP was disabled for a while, thus serving PHP as plain tex/html. You might also (I hope) be getting a cached version from somewhere.

I've revved the filenames for the pertinent external JS files, which might help. Try refreshing again, and see if there's any difference. I've also included a time stamp at the very bottom of the page source (view source and scroll to the closing `</body>` tag – just before it you should see the date and time). If you're not getting this, you're seeing a cached version.

@Mattvic If you're still getting raw PHP, please let me know, as this needs looking at!

**Comment by ghost** [comment]
I think the problem is solved: the slideshows work for me with Chrome (tested on two different laptops, with extensions enabled). 

@reallsimple Many thanks for your help! It´s a great slider and I´m happy I can use it now.

**Comment by agami** [comment]
Seconded - whatever you changed did the trick!

**Comment by andygott** [comment]
Good news! Thank you both for the feedback and help with debugging this – invaluable when I can't replicate the problem! In Hope you get good use out of the plugin.

In case anyone is interested in the technical issues behind this, I'll post about it on the Really Simple blog withing the next few days.

Andy

[Update: fix now pushed to Github and available in the latest release.]

**Comment by mattwojas** [comment]
I am still experiencing this problem in Chrome - the first image shows, and when it is supposed to fade, it just shows a white background.  There is no errors in the console, and I don't see anything else that could be wrong.  I have downloaded the latest from the website.  I am using windows7 64bit, Chrome v: 14.0.835.202 m

-some more info - the code is working in the developer tools window - I can watch the opacity change.  If I alter a style the image will show, but fade, just frozen in whatever state it was in at that point (half tranpsparent sometimes, more or less other times).

the examples from the website work.  I am not sure what the problem is, if you find any info please help!

**Comment by andygott** [comment]
Are the demos working for you at: http://reallysimpleworks.com/slideshow/ ?

**Comment by mattwojas** [comment]
Yes, the demos are working, I thought maybe it was a different version of JQuery but it doesn't seem to matter.

**Comment by andygott** [comment]
Have you tried it with the original CSS, from the packaged demos? Does it work? Your CSS may be conflicting with the plugin.
